# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            gophercloud
tagline:          'The OpenStack SDK for Go'
description:      'Gophercloud is an open-source library for working with OpenStack clouds in golang.'
url:              http://gophercloud.io
baseurl:          /
paginate:         5

# Custom vars
version:          0.0.2

links:
  install:        /installation
  contrib:        https://github.com/rackspace/gophercloud/blob/master/CONTRIBUTING.md
  docs:           /docs
  github:         https://github.com/rackspace/gophercloud
  godoc:          http://godoc.org/github.com/rackspace/gophercloud
  hyde:           https://github.com/poole/hyde
